version: '3.8'

services:
  postgis:
    image: postgis/postgis:16-3.4-alpine
    container_name: WTB--Database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - WTB--Database:/var/lib/postgresql/data
    command: ["postgres", "-c", "timezone=Asia/Jakarta"]

volumes:
  WTB--Database:
